apiVersion: v1
kind: Service
metadata:
  name: ennui-agents-core
  labels:
    app: ennui-agents-core
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ennui-agents-core
